#!/bin/bash
#
# useful little script I wrote to have fun while updating homebrew
# 
# last update 12/31/20
#
COLORTEXT='\033[1;34m' # light blue

printf "${COLORTEXT}Updating homebrew on $(date)..."

printf "\n${COLORTEXT}Updating local base of available packages and versions..."
brew update       # update local base of available packages and versions

brew upgrade      # install new versions of outdated packages        

printf "${COLORTEXT}Cleaning cache of unfinished downloads...\n"
brew cleanup      # cache cleanup of unfinished downloads

printf "${COLORTEXT}Running brew doctor in case there are issues...\n"
brew doctor       # show problems if any
