#!/bin/bash
#
# useful little script I wrote to have fun while updating homebrew

printf "\n\033[1;35mUpdating homebrew from bash script on $(date)..."

printf "\nUpdating local base of available packages and versions..."
brew update       # update local base of available packages and versions

echo "install new versions of outdated packages..."
brew upgrade      # install new versions of outdated packages        

echo "running brew cleanup to clean cache of unfinished downloads..."
brew cleanup      # cache cleanup of unfinished downloads

echo "running brew doctor..."
brew doctor       # show problems if any
